---
title: Collins Kiptum
email: collinsrotichia@gmail.com
description: Jambo! I am Collins- an aspiring Network and Cloud Security
  Engineer blending passion, persistence and hands-on learning.Dive into my
  projects, my labs and the tools I use to shape the future of secure
  communication environments.
twitter_username: collo_tum
github_username: CollinsKiptum1
minimal_mistakes_skin: neon
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: null
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
author:
  name: Collins Kiptum
  avatar: /assets/images/bio-photo.jpg
  bio: " Network Engineer | Cloud & Network security | Lifelong Learner | Building
    Secure Systems"
  links:
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/collins-kiptum/
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/
    - label: Discord
      icon: fab fa-fw fa-discord
      url: https://discord.com/users/1036554785182191627/
footer:
  links:
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/collins-kiptum/
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/
    - label: Discord
      icon: fab fa-fw fa-discord
      url: https://discord.com/users/1036554785182191627/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
